{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6faeeb6e-d2b6-4e7d-bae7-84f5a59c6faa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset loaded successfully.\n",
      "Number of rows: 300\n",
      "Number of columns: 16\n",
      "\n",
      "==============================\n",
      "PREPROCESSING COMPLETE\n",
      "==============================\n",
      "\n",
      "Processed dataset:\n",
      "   age  quiz1_marks  quiz2_marks  quiz3_marks  total_assignments  \\\n",
      "0   19          8.0          5.7          7.4                  5   \n",
      "1   21         10.0          7.9          4.1                  5   \n",
      "2   19          7.5          1.2          0.3                  5   \n",
      "3   21          5.2          2.5          9.9                  5   \n",
      "4   21          5.9          6.3          2.0                  5   \n",
      "\n",
      "   midterm_marks  previous_gpa  total_lectures  lectures_attended  \\\n",
      "0           30.0          2.57              12                  4   \n",
      "1           25.4          2.40              12                  1   \n",
      "2           14.4          2.99              12                  0   \n",
      "3           17.7          1.68              12                  9   \n",
      "4           23.8          2.53              12                  7   \n",
      "\n",
      "   total_lab_sessions  labs_attended  lecture_attendance_rate  \\\n",
      "0                   6              1                33.333333   \n",
      "1                   6              5                 8.333333   \n",
      "2                   6              0                 0.000000   \n",
      "3                   6              0                75.000000   \n",
      "4                   6              4                58.333333   \n",
      "\n",
      "   lab_attendance_rate  quiz_average  lowest_quiz_mark  highest_quiz_mark  \\\n",
      "0            16.666667      7.033333               5.7                8.0   \n",
      "1            83.333333      7.333333               4.1               10.0   \n",
      "2             0.000000      3.000000               0.3                7.5   \n",
      "3             0.000000      5.866667               2.5                9.9   \n",
      "4            66.666667      4.733333               2.0                6.3   \n",
      "\n",
      "   quiz_performance_range  current_performance  gender_Male  \n",
      "0                     2.3            18.516667            1  \n",
      "1                     5.9            16.366667            1  \n",
      "2                     7.2             8.700000            0  \n",
      "3                     7.4            11.783333            1  \n",
      "4                     4.3            14.266667            0  \n",
      "\n",
      "Processed columns:\n",
      "['age', 'quiz1_marks', 'quiz2_marks', 'quiz3_marks', 'total_assignments', 'midterm_marks', 'previous_gpa', 'total_lectures', 'lectures_attended', 'total_lab_sessions', 'labs_attended', 'lecture_attendance_rate', 'lab_attendance_rate', 'quiz_average', 'lowest_quiz_mark', 'highest_quiz_mark', 'quiz_performance_range', 'current_performance', 'gender_Male']\n",
      "\n",
      "Missing values:\n",
      "age                        0\n",
      "quiz1_marks                0\n",
      "quiz2_marks                0\n",
      "quiz3_marks                0\n",
      "total_assignments          0\n",
      "midterm_marks              0\n",
      "previous_gpa               0\n",
      "total_lectures             0\n",
      "lectures_attended          0\n",
      "total_lab_sessions         0\n",
      "labs_attended              0\n",
      "lecture_attendance_rate    0\n",
      "lab_attendance_rate        0\n",
      "quiz_average               0\n",
      "lowest_quiz_mark           0\n",
      "highest_quiz_mark          0\n",
      "quiz_performance_range     0\n",
      "current_performance        0\n",
      "gender_Male                0\n",
      "dtype: int64\n",
      "\n",
      "Processed dataset saved as 'processed_student_data.csv'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8244\\1284110331.py:79: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.\n",
      "See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.\n",
      "  categorical_columns = df.select_dtypes(\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8244\\1284110331.py:240: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.\n",
      "See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.\n",
      "  categorical_columns = df.select_dtypes(\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 1. LOAD DATASET\n",
    "# ============================================================\n",
    "\n",
    "def load_data(file_path):\n",
    "    \"\"\"\n",
    "    Load the student dataset from a CSV file.\n",
    "    \"\"\"\n",
    "\n",
    "    df = pd.read_csv(file_path)\n",
    "\n",
    "    print(\"Dataset loaded successfully.\")\n",
    "    print(\"Number of rows:\", df.shape[0])\n",
    "    print(\"Number of columns:\", df.shape[1])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 2. REMOVE UNNECESSARY COLUMNS\n",
    "# ============================================================\n",
    "\n",
    "def remove_unnecessary_columns(df):\n",
    "    \"\"\"\n",
    "    Remove columns that should not be used by the ML model.\n",
    "    \"\"\"\n",
    "\n",
    "    columns_to_remove = []\n",
    "\n",
    "    # Student ID and name are identifiers, not useful\n",
    "    # predictive features.\n",
    "    if \"student_id\" in df.columns:\n",
    "        columns_to_remove.append(\"student_id\")\n",
    "\n",
    "    if \"name\" in df.columns:\n",
    "        columns_to_remove.append(\"name\")\n",
    "\n",
    "    # assignments_submitted is completely empty\n",
    "    # in the current dataset.\n",
    "    if \"assignments_submitted\" in df.columns:\n",
    "        if df[\"assignments_submitted\"].isna().all():\n",
    "            columns_to_remove.append(\"assignments_submitted\")\n",
    "\n",
    "    df = df.drop(\n",
    "        columns=columns_to_remove,\n",
    "        errors=\"ignore\"\n",
    "    )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 3. HANDLE MISSING VALUES\n",
    "# ============================================================\n",
    "\n",
    "def handle_missing_values(df):\n",
    "    \"\"\"\n",
    "    Handle missing values in the dataset.\n",
    "    \"\"\"\n",
    "\n",
    "    # Numeric columns\n",
    "    numeric_columns = df.select_dtypes(\n",
    "        include=[\"int64\", \"float64\"]\n",
    "    ).columns\n",
    "\n",
    "    for column in numeric_columns:\n",
    "\n",
    "        if df[column].isna().sum() > 0:\n",
    "\n",
    "            df[column] = df[column].fillna(\n",
    "                df[column].median()\n",
    "            )\n",
    "\n",
    "    # Categorical columns\n",
    "    categorical_columns = df.select_dtypes(\n",
    "        include=[\"object\"]\n",
    "    ).columns\n",
    "\n",
    "    for column in categorical_columns:\n",
    "\n",
    "        if df[column].isna().sum() > 0:\n",
    "\n",
    "            df[column] = df[column].fillna(\n",
    "                df[column].mode()[0]\n",
    "            )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 4. CREATE ATTENDANCE FEATURES\n",
    "# ============================================================\n",
    "\n",
    "def create_attendance_features(df):\n",
    "    \"\"\"\n",
    "    Create attendance percentage features.\n",
    "    \"\"\"\n",
    "\n",
    "    # Lecture attendance percentage\n",
    "    if (\n",
    "        \"lectures_attended\" in df.columns\n",
    "        and \"total_lectures\" in df.columns\n",
    "    ):\n",
    "\n",
    "        df[\"lecture_attendance_rate\"] = np.where(\n",
    "            df[\"total_lectures\"] > 0,\n",
    "            (df[\"lectures_attended\"] /\n",
    "             df[\"total_lectures\"]) * 100,\n",
    "            0\n",
    "        )\n",
    "\n",
    "    # Laboratory attendance percentage\n",
    "    if (\n",
    "        \"labs_attended\" in df.columns\n",
    "        and \"total_lab_sessions\" in df.columns\n",
    "    ):\n",
    "\n",
    "        df[\"lab_attendance_rate\"] = np.where(\n",
    "            df[\"total_lab_sessions\"] > 0,\n",
    "            (df[\"labs_attended\"] /\n",
    "             df[\"total_lab_sessions\"]) * 100,\n",
    "            0\n",
    "        )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 5. CREATE QUIZ FEATURES\n",
    "# ============================================================\n",
    "\n",
    "def create_quiz_features(df):\n",
    "    \"\"\"\n",
    "    Create features based on quiz performance.\n",
    "    \"\"\"\n",
    "\n",
    "    quiz_columns = [\n",
    "        \"quiz1_marks\",\n",
    "        \"quiz2_marks\",\n",
    "        \"quiz3_marks\"\n",
    "    ]\n",
    "\n",
    "    # Check that all quiz columns exist\n",
    "    if all(column in df.columns for column in quiz_columns):\n",
    "\n",
    "        # Average quiz mark\n",
    "        df[\"quiz_average\"] = df[quiz_columns].mean(\n",
    "            axis=1\n",
    "        )\n",
    "\n",
    "        # Lowest quiz mark\n",
    "        df[\"lowest_quiz_mark\"] = df[quiz_columns].min(\n",
    "            axis=1\n",
    "        )\n",
    "\n",
    "        # Highest quiz mark\n",
    "        df[\"highest_quiz_mark\"] = df[quiz_columns].max(\n",
    "            axis=1\n",
    "        )\n",
    "\n",
    "        # Difference between highest and lowest quiz\n",
    "        df[\"quiz_performance_range\"] = (\n",
    "            df[\"highest_quiz_mark\"]\n",
    "            - df[\"lowest_quiz_mark\"]\n",
    "        )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 6. CREATE PERFORMANCE FEATURES\n",
    "# ============================================================\n",
    "\n",
    "def create_performance_features(df):\n",
    "    \"\"\"\n",
    "    Create additional academic performance features.\n",
    "    \"\"\"\n",
    "\n",
    "    # Average of quiz and midterm marks\n",
    "    if (\n",
    "        \"quiz_average\" in df.columns\n",
    "        and \"midterm_marks\" in df.columns\n",
    "    ):\n",
    "\n",
    "        df[\"current_performance\"] = (\n",
    "            df[\"quiz_average\"]\n",
    "            + df[\"midterm_marks\"]\n",
    "        ) / 2\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 7. REMOVE DATA LEAKAGE COLUMNS\n",
    "# ============================================================\n",
    "\n",
    "def remove_leakage_columns(df):\n",
    "    \"\"\"\n",
    "    Remove columns that represent future outcomes.\n",
    "\n",
    "    These columns should NOT be used to predict whether\n",
    "    a student is at risk before the final outcome occurs.\n",
    "    \"\"\"\n",
    "\n",
    "    leakage_columns = []\n",
    "\n",
    "    # Final marks represent the later/final outcome.\n",
    "    # It should not be used as an input feature when\n",
    "    # predicting risk before the final examination.\n",
    "    if \"final_marks\" in df.columns:\n",
    "        leakage_columns.append(\"final_marks\")\n",
    "\n",
    "    # Overall score is also likely to contain final outcome\n",
    "    # information, so remove it if it exists.\n",
    "    if \"overall_score\" in df.columns:\n",
    "        leakage_columns.append(\"overall_score\")\n",
    "\n",
    "    df = df.drop(\n",
    "        columns=leakage_columns,\n",
    "        errors=\"ignore\"\n",
    "    )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 8. ENCODE CATEGORICAL VARIABLES\n",
    "# ============================================================\n",
    "\n",
    "def encode_categorical_variables(df):\n",
    "    \"\"\"\n",
    "    Convert categorical variables such as gender into\n",
    "    numerical columns.\n",
    "    \"\"\"\n",
    "\n",
    "    categorical_columns = df.select_dtypes(\n",
    "        include=[\"object\"]\n",
    "    ).columns\n",
    "\n",
    "    if len(categorical_columns) > 0:\n",
    "\n",
    "        df = pd.get_dummies(\n",
    "            df,\n",
    "            columns=categorical_columns,\n",
    "            drop_first=True,\n",
    "            dtype=int\n",
    "        )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 9. COMPLETE PREPROCESSING PIPELINE\n",
    "# ============================================================\n",
    "\n",
    "def preprocess_data(\n",
    "    file_path,\n",
    "    remove_future_outcomes=True\n",
    "):\n",
    "    \"\"\"\n",
    "    Complete preprocessing pipeline.\n",
    "\n",
    "    Returns:\n",
    "        processed_df\n",
    "    \"\"\"\n",
    "\n",
    "    # Load\n",
    "    df = load_data(file_path)\n",
    "\n",
    "    # Remove unnecessary columns\n",
    "    df = remove_unnecessary_columns(df)\n",
    "\n",
    "    # Handle missing values\n",
    "    df = handle_missing_values(df)\n",
    "\n",
    "    # Feature engineering\n",
    "    df = create_attendance_features(df)\n",
    "\n",
    "    df = create_quiz_features(df)\n",
    "\n",
    "    df = create_performance_features(df)\n",
    "\n",
    "    # Remove future outcome columns\n",
    "    if remove_future_outcomes:\n",
    "        df = remove_leakage_columns(df)\n",
    "\n",
    "    # Encode categorical variables\n",
    "    df = encode_categorical_variables(df)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 10. MAIN PROGRAM\n",
    "# ============================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    file_path = \"student_dropout_behavior_dataset.csv\"\n",
    "\n",
    "    processed_df = preprocess_data(\n",
    "        file_path\n",
    "    )\n",
    "\n",
    "    print(\"\\n==============================\")\n",
    "    print(\"PREPROCESSING COMPLETE\")\n",
    "    print(\"==============================\")\n",
    "\n",
    "    print(\"\\nProcessed dataset:\")\n",
    "    print(processed_df.head())\n",
    "\n",
    "    print(\"\\nProcessed columns:\")\n",
    "    print(processed_df.columns.tolist())\n",
    "\n",
    "    print(\"\\nMissing values:\")\n",
    "    print(processed_df.isnull().sum())\n",
    "\n",
    "    # Save processed dataset\n",
    "    processed_df.to_csv(\n",
    "        \"processed_student_data.csv\",\n",
    "        index=False\n",
    "    )\n",
    "\n",
    "    print(\n",
    "        \"\\nProcessed dataset saved as \"\n",
    "        \"'processed_student_data.csv'\"\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbb06f6c-7c6e-4242-981a-debf154d65f0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
